### ISSUE TITLE
Cant install bcrypt-ruby gem using bundler

### ISSUE THREAD

**Issue by sammdec** [rbenv/rbenv#364]
`gem install` works but `bundle install` fails with Bundler version 1.3.1:

```
Installing bcrypt-ruby (3.0.1) 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

/Users/sam/.rbenv/versions/1.9.3-p392/bin/ruby extconf.rb 
/Users/sam/.rbenv/versions/1.9.3-p392/bin/ruby: invalid option -R  (-h will show valid options) (RuntimeError)
```

`.bundle/config`:

``` yml

---
BUNDLE_PATH: ./vendor/bundle
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

run `which -a bundle` = `/Users/sam/.rbenv/shims/bundle`
run `rbenv hooks exec` = Doesn't output anything

gem env:

``` yml
    RubyGems Environment:
    - RUBYGEMS VERSION: 2.0.2
    - RUBY VERSION: 1.9.3 (2013-02-22 patchlevel 392) [x86_64-darwin12.2.1]
    - INSTALLATION DIRECTORY: /Users/sam/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1
    - RUBY EXECUTABLE: /Users/sam/.rbenv/versions/1.9.3-p392/bin/ruby
    - EXECUTABLE DIRECTORY: /Users/sam/.rbenv/versions/1.9.3-p392/bin
    - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-12
    - GEM PATHS:
     - /Users/sam/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1
     - /Users/sam/.gem/ruby/1.9.1
    - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-rdoc --no-ri"
     - "update" => "--no-rdoc --no-ri"
    - REMOTE SOURCES:
     - https://rubygems.org/
```
